### ISSUE TITLE
Ways to help and contribute to the Platform’s UI/UX

### ISSUE THREAD

**Issue by anajsana** [bukosabino/justicio#64]
I’m interested in contributing to this initiative and was wondering if there are any plans in the project roadmap to focus on enhancing the UI/UX aspect. If so, I'd like to know where additional support might be needed to help out 🙂

Do you hold regular meetings to align on next steps, or is there a mailing list I could join? Thank you in advance for the great work 🙏

**Comment by adantart** [comment]
Hola Ana!!!
Te contesto en español aprovechando que hablas el idioma. Aunque el repo esté en inglés por "internacionalizar" el proyecto ;-)
Contacta conmigo a través de alex (arroba) justicio.es , quedamos y te cuento el proyecto y la forma en la que podrías colaborar. De primeras te agradezco ya tu interés y encantados de que el equipo se haga más grande  ;-)
Un saludo !

**Comment by anajsana** [comment]
Genial! email enviado 👍 Muhcas Gracias 🙂

**Comment by anajsana** [comment]
I'm closing this issue since this was already solved and currently helping in the ETLS module 👍 Gracias!
